ej:
  zk:
    server-lists: localhost:2181
    namespace: ej-namespace
server:
  port: 0

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://localhost:3306/elastic_job?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    url: jdbc:p6spy:mysql://localhost:3306/elastic_job?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
